services:
  - type: web
    name: babcock-smart-campus-backend
    env: python
    region: oregon
    plan: free
    # Force redeploy with latest fixes
    buildCommand: |
      python --version
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn app.flask_main:app --bind 0.0.0.0:$PORT --workers 1
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: DEMO_MODE
        value: true
      - key: DEBUG
        value: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: babcock_smart_campus
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: REFRESH_TOKEN_EXPIRE_DAYS
        value: 7
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: CORS_ORIGINS
        value: "*"
    healthCheckPath: /health
    autoDeploy: true
    branch: main 