name = "smart-campus-backend"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "pip install -r requirements.txt"

[env.production]
name = "smart-campus-backend-prod"

[env.staging]
name = "smart-campus-backend-staging"

[[pages]]
name = "smart-campus-backend"
route = "/*"
script = "app/main.py"
